// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {caching} from '../models';
import {domain} from '../models';

export function OpenExcelFile():Promise<string>;

export function OrdersByFilter(arg1:caching.OrderFilter):Promise<Array<domain.Order>>;

export function OrdersCities():Promise<Array<string>>;

export function OrdersPlatformNames():Promise<Array<string>>;

export function ParseOrdersExcelFile(arg1:string,arg2:string):Promise<void>;

export function SheetsFromExcelFile(arg1:string):Promise<Array<string>>;
