// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OrdersByFilter(arg1) {
  return window['go']['main']['App']['OrdersByFilter'](arg1);
}

export function ParseOrdersExcelFile(arg1, arg2) {
  return window['go']['main']['App']['ParseOrdersExcelFile'](arg1, arg2);
}

export function SheetsFromExcelFile(arg1) {
  return window['go']['main']['App']['SheetsFromExcelFile'](arg1);
}
